name: test

on: [ push ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 10.x, 12.x, 14.x, 15.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-build-${{ env.cache-name }}-
            ${{ matrix.os }}-build-
            ${{ matrix.os }}-

      - name: Install Dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Install CodeCov
        run: npm install -g codecov

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info
          name: ${{ matrix.os }}, node ${{ matrix.node-version }}
